# Generated by Django 3.1.2 on 2020-11-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Componente', '0002_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fotografia',
            field=models.ImageField(upload_to='productos'),
        ),
    ]
